"""Sourceless launcher. Generated by scripts/obfuscate_project.py."""
from __future__ import annotations
import importlib.util
import pathlib
import sys
import threading

REQUIRED = (3, 10)

# Keep local route wrappers from regenerating tracked release bytecode files.
sys.dont_write_bytecode = True

_US_TO_SG = {
    "https://dreamina-api.us.capcut.com": "https://mweb-api-sg.capcut.com",
    "https://commerce.us.capcut.com": "https://commerce-api-sg.capcut.com",
}


_patch_attempts = 0

def _patch_dreamina_region():
    """Redirect US-datacenter API URLs to SG for JP/SG-region accounts."""
    global _patch_attempts
    _patch_attempts += 1
    mod = None
    mod_key = None
    for key, m in sys.modules.items():
        if "jimeng_task_executor" in key:
            mod = m
            mod_key = key
            break
    if mod is None:
        if _patch_attempts <= 20:
            threading.Timer(3.0, _patch_dreamina_region).start()
            if _patch_attempts % 5 == 0:
                print(f"[region-patch] Attempt {_patch_attempts}: jimeng_task_executor not yet in sys.modules, retrying...")
        else:
            print("[region-patch] FAILED: jimeng_task_executor never appeared in sys.modules after 60s")
            print(f"[region-patch] Available modules containing 'jimeng': {[k for k in sys.modules if 'jimeng' in k]}")
            print(f"[region-patch] Available modules containing 'executor': {[k for k in sys.modules if 'executor' in k]}")
        return
    print(f"[region-patch] Found module as '{mod_key}' on attempt {_patch_attempts}")
    patched = []
    for attr in ("_DREAMINA_API_BASE",):
        old = getattr(mod, attr, None)
        if old and old in _US_TO_SG:
            setattr(mod, attr, _US_TO_SG[old])
            patched.append(f"{attr}: {old} -> {_US_TO_SG[old]}")
    for attr in (
        "_DREAMINA_CREDITS_URL",
        "_DREAMINA_USER_CREDIT_URL",
        "_DREAMINA_SUBSCRIPTION_USER_INFO_URL",
    ):
        old = getattr(mod, attr, None)
        if old:
            new = old
            for us, sg in _US_TO_SG.items():
                new = new.replace(us, sg)
            if new != old:
                setattr(mod, attr, new)
                patched.append(f"{attr}: ...us... -> ...sg...")
    if patched:
        print(f"[region-patch] Patched {len(patched)} Dreamina URLs to SG datacenter")
        for p in patched:
            print(f"  {p}")


def _run_pyc() -> None:
    if sys.implementation.name != "cpython" or sys.version_info[:2] != REQUIRED:
        raise SystemExit(
            "This release was built for CPython "
            f"{REQUIRED[0]}.{REQUIRED[1]}.x, current is {sys.version.split()[0]}."
        )
    pyc = pathlib.Path(__file__).with_suffix(".pyc")
    spec = importlib.util.spec_from_file_location("__main__", pyc)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {pyc}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["__main__"] = module
    threading.Timer(2.0, _patch_dreamina_region).start()
    spec.loader.exec_module(module)


if __name__ == "__main__":
    _run_pyc()
